# Netlify configuration for NFT Marketplace Backend
[build]
  # Build command for NestJS
  command = "pnpm run build"
  
  # Functions directory
  functions = "dist"
  
  # Node.js version and environment variables
[build.environment]
  NODE_VERSION = "18"
  # Server Configuration
  PORT = "8081"
  NODE_ENV = "production"
  FRONTEND_URL = "https://nft-market-tuna.netlify.app"

  # JWT Configuration
  JWT_SECRET = "nft2025"
  JWT_EXPIRES_IN = "7d"

  # Firebase Configuration
  FIREBASE_PROJECT_ID = "lavie-196cd"
  FIREBASE_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDQYyVw9i5KUXAL\nSpRj4LXYPC2KHBJsFig0stmYYVOm+zOBRFOdl+llIuejQ//ktcC71srRuIFsJOiL\nRmLlJrn5zuqpjKcJKVOD30F3PwXipS8/nsQsjCRvAb73EWRQTgrqL9NpSUNHdtz3\nMDW71bHJtQEgy6x1uO9Xn2thwsOBVB/jrTaiUm25iWpysI2mkFOCU7Qpod4QwR1F\n8jOqANChX/6/UbwHU8ctYBK+1Z6EM2FbWOF49UxiCdaNQLLLplJuiVmGag/7rW/z\nqDrlolc8kqZnzQPnv5BK7mu1vfmZ1rALOrp2Pt5Qdai8bOyh5TpLv+d6XmlR7Xb/\ndxVYGlm5AgMBAAECggEACwgJ8LOXj7zv6X5xNzhWErRc1MrXpCZ9dQy4EtD+1KrH\noeLev6D4bK+EWP2TNlBI0P4gjn7t8Fj5K9D2EJtpjPKJ3vU1185QQCg5bE6cc9Bl\ncpYSXH6uubxQl6kGs8RDNP0t0TeyUBOCxF3Q+mM9nifu1LBI2OfermIfanVyVA4/\ncjaaGycudxRf/XEXxdlMwI8iWxevAJaXlE6IB/0MeAUw+myQeY3IvdnhExyYHNoQ\noEIQTD/CZMHWI6il5MYHgMsxAlZHj88XVUTLV+/SjDPy1YjjLVca0ANmeBuNdX2a\nUyoN3xrJ6/F1hW4wW8OdUFuUxmrNxSd8pVxbK4iP4QKBgQD9o4RljIilyIsSBlj0\nRIAQ+9ssKAUEukhAdVXEMwIslwrd2xmpzISOfEAT4uVEEdW+e04/L41++P4kyRss\nJf7BoPGv3ruKHJLkQV2Bd31mUx96GXRqgoCtiz8hTYaCKT0Ba7J0gb8fzekGyJng\nGezQboSfWSPuLd/jbR6jb0WQowKBgQDSU8irkajM/S46xf18iSRV3lZ4sMkqMN6U\nx4CRONViJC8T7tRKctIzTr4VHp6m4l1txawkejNdT4v4/FDl4MpGgp7Pa7gGTsXM\n5lQfy8VSzdDoT3LqAYLCvXSRYS4zegQmNCpWM50vKC2uO/ZvKpqrr7YVBLpFOn2a\nfpgo6lOl8wKBgF9pPGuq0thyOQZdxuaUQgyhgU/5+fFOVdGRkeLNQVsesmLEgcHj\nAlZLHRud9ZqGjv4pikSwkaya45dY41TXMh8KeQAsbCXHG+arRA5osY5lZGjc3HMY\nhmlCAUx4ykl6U82OAsJa8Fd5cNgxa9jmR7Qcbt02fhKhxR/bM3RNbkC7AoGAeh3h\nPhQ1QMejJsa71am+qgiMhkiGk/OJ2DI5KJgp9HBz0QvywEMIXnfSj2qWzOhTPJ/v\nwcIdvoioCWleAwpQBz5hvKabUzY7TCtTHp7uM5SCPc+bNdioti7P1nTpIUQv0oqp\nJiGTmsSmOSphe8vtv88mVe/HwtgiAyiLaf4bkRcCgYEApOAOtyA0s/5vAYbqU1zb\nXM9q3DDot2r670keWMsj2K94u0BnKEUp/oTQ8aPeX/uupQN6eE5U/Pc1ejWK7Ozr\ngsq2VRyTU0PqMO7QCL082wiNqCT3Eh1Rr+2sNPuV9k3BXFfnzpotfluXTbFgfeF3\njwZnJIHLQoJNBA7+kB1rAGY=\n-----END PRIVATE KEY-----\n"
  FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@lavie-196cd.iam.gserviceaccount.com"
  FIREBASE_API_KEY = "AIzaSyDbyPtD6BVEbefBieILYeBjLCS35abN7aM"
  FIREBASE_AUTH_DOMAIN = "lavie-196cd.firebaseapp.com"
  FIREBASE_STORAGE_BUCKET = "lavie-196cd.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID = "631172388937"
  FIREBASE_APP_ID = "1:631172388937:web:3de000ee30131caeba4798"
  FIREBASE_MEASUREMENT_ID = "G-HVM047V56C"

  # OpenZeppelin Defender Configuration
  DEFENDER_API_KEY = "ArjaqtuKsioJW62cJTKE82nL5npde2sB"
  DEFENDER_API_SECRET = "4vQda3ErS7sourdyeetw8B1FSpGSwaChQNonPHKatjPqqkxSk8wGvBRKQA8h7MJA"
  DEFENDER_RELAYER_ADDRESS = "0x2ba190287a390cfa282E4B9aE57F758F28BA96d5"
  DEFENDER_RELAYER_ID = "ffd9488c-0af9-4c0a-8d3c-29e199a1c8c9"
  DEFENDER_MINT_AUTOTASK_ID = "7d0bc3c1-7578-472e-afdf-8d03d4c6611b"
  DEFENDER_TRANSFER_AUTOTASK_ID = "e9219e0c-c338-408e-b668-06cafb64cd1c"
  DEFENDER_QUERY_AUTOTASK_ID = "118413eb-f845-40c5-83da-288b32a1862a"

  # Webhook URLs
  DEFENDER_MINT_WEBHOOK_URL = "https://api.defender.openzeppelin.com/actions/7d0bc3c1-7578-472e-afdf-8d03d4c6611b/runs/webhook/358d6c75-54ec-49b9-bc3d-a558293d8ce0/BVjG5mR1Rx3m1X9ESGdhUp"
  DEFENDER_TRANSFER_WEBHOOK_URL = "https://api.defender.openzeppelin.com/autotasks/e9219e0c-c338-408e-b668-06cafb64cd1c/runs/webhook/EseGNoLu9dNxuZtaHVG8bu"
  DEFENDER_QUERY_WEBHOOK_URL = "https://api.defender.openzeppelin.com/autotasks/118413eb-f845-40c5-83da-288b32a1862a/runs/webhook/7U65Gq8YtAiYyV7gfNCmfw"

  # Blockchain Configuration
  NETWORK_NAME = "polygon-amoy"
  RPC_URL = "https://rpc-amoy.polygon.technology"
  CONTRACT_ADDRESS = "0x5B8c37aBdd3Dc72874d20a9403549798309599b5"
  CHAIN_ID = "80002"
  BLOCK_EXPLORER = "https://amoy.polygonscan.com/"

  # Encryption Key for wallet private keys
  ENCRYPTION_KEY = "15f4d1b5978b4008d624d27a9894210c0d9ddcf1e8bfe7f593cb4f5995bd4270"

  # IPFS Configuration (Pinata)
  PINATA_API_KEY = "f95bfdf8b3f6139ef103"
  PINATA_SECRET_KEY = "57421dc41de62128b6b66696a7f53b5ccf87c6241afc95ce9da0d33914075901"
  PINATA_JWT = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySW5mb3JtYXRpb24iOnsiaWQiOiJiZDk4ZGFlMC1mODg5LTQxNDItOTk0Zi0yNmEwOTc1ODQ0NjQiLCJlbWFpbCI6InR1bmdjYW4yMDAwQGdtYWlsLmNvbSIsImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJwaW5fcG9saWN5Ijp7InJlZ2lvbnMiOlt7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6IkZSQTEifSx7ImRlc2lyZWRSZXBsaWNhdGlvbkNvdW50IjoxLCJpZCI6Ik5ZQzEifV0sInZlcnNpb24iOjF9LCJtZmFfZW5hYmxlZCI6ZmFsc2UsInN0YXR1cyI6IkFDVElWRSJ9LCJhdXRoZW50aWNhdGlvblR5cGUiOiJzY29wZWRLZXkiLCJzY29wZWRLZXlLZXkiOiJmOTViZmRmOGIzZjYxMzllZjEwMyIsInNjb3BlZEtleVNlY3JldCI6IjU3NDIxZGM0MWRlNjIxMjhiNmI2NjY5NmE3ZjUzYjVjY2Y4N2M2MjQxYWZjOTVjZTlkYTBkMzM5MTQwNzU5MDEiLCJleHAiOjE3ODUzMjE2Mzl9.ucdxTyPse2dLOcQQWoyqeRrxURxPZeWhAI5C2hNKlWA"
  IPFS_GATEWAY = "https://gateway.pinata.cloud/ipfs/"

  # Moralis v2 Configuration
  MORALIS_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6ImJhMGY0NmEzLWEzZDAtNDY1NC05OTk1LTQ0ZTg3ODQzOTU0NCIsIm9yZ0lkIjoiNDYyMTczIiwidXNlcklkIjoiNDc1NDgyIiwidHlwZUlkIjoiNzg3NDdiNTctOTMzOC00MjE1LTgwZDctN2Q2MmRiNjdmMzU3IiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NTM3ODczMjYsImV4cCI6NDkwOTU0NzMyNn0.FJljYq8LbO4Uh6c-2gRuAvaSzc-8xV_Lt1gyazQe8Ew"

  # Hardhat Configuration (for deployment)
  PRIVATE_KEY = "6b5af3cb8a0417eeb39b1af872153b214a57abf4e445cca9cbc7f1a386007d46"
  POLYGON_RPC_URL = "https://rpc-amoy.polygon.technology"
  POLYGONSCAN_API_KEY = "7BBQ9JF4T2M26QIA5M8E8HNPW58MNQISUP"

  # Webhook Configuration
  WEBHOOK_URL = "https://nft-market-api.netlify.app/api/webhook"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# CORS headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
