# Netlify configuration for NFT Marketplace Backend
[build]
  # Build command for NestJS
  command = "pnpm run build"
  
  # Functions directory
  functions = "dist"
  
  # Node.js version
  environment = { NODE_VERSION = "18" }

# Environment variables for backend
[build.environment]
  # Server Configuration
  PORT = "8081"
  NODE_ENV = "production"
  
  # JWT Configuration
  JWT_SECRET = "your_strong_jwt_secret_here"
  JWT_EXPIRES_IN = "7d"
  
  # Firebase Configuration
  FIREBASE_PROJECT_ID = "lavie-196cd"
  FIREBASE_CLIENT_EMAIL = "firebase-adminsdk-fbsvc@lavie-196cd.iam.gserviceaccount.com"
  FIREBASE_API_KEY = "AIzaSyDbyPtD6BVEbefBieILYeBjLCS35abN7aM"
  FIREBASE_AUTH_DOMAIN = "lavie-196cd.firebaseapp.com"
  FIREBASE_STORAGE_BUCKET = "lavie-196cd.firebasestorage.app"
  FIREBASE_MESSAGING_SENDER_ID = "631172388937"
  FIREBASE_APP_ID = "1:631172388937:web:abcdefghijklmnopqr"
  
  # OpenZeppelin Defender Configuration
  DEFENDER_API_KEY = "your_defender_api_key"
  DEFENDER_API_SECRET = "your_defender_api_secret"
  DEFENDER_MINT_WEBHOOK_URL = "https://api.defender.openzeppelin.com/actions/7d0bc3c1-7578-472e-afdf-8d03d4c6611b/runs/webhook/358d6c75-54ec-49b9-bc3d-a558293d8ce0/BVjG5mR1Rx3m1X9ESGdhUp"
  
  # Blockchain Configuration
  CONTRACT_ADDRESS = "0x5B8c37aBdd3Dc72874d20a9403549798309599b5"
  RPC_URL = "https://rpc-amoy.polygon.technology"
  PRIVATE_KEY = "6b5af3cb8a0417eeb39b1af872153b214a57abf4e445cca9cbc7f1a386007d46"
  POLYGON_RPC_URL = "https://rpc-amoy.polygon.technology"
  POLYGONSCAN_API_KEY = "7BBQ9JF4T2M26QIA5M8E8HNPW58MNQISUP"
  
  # Moralis Configuration
  MORALIS_API_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJub25jZSI6ImJhMGY0NmEzLWEzZDAtNDY1NC05OTk1LTQ0ZTg3ODQzOTU0NCIsIm9yZ0lkIjoiNDYyMTczIiwidXNlcklkIjoiNDc1NDgyIiwidHlwZUlkIjoiNzg3NDdiNTctOTMzOC00MjE1LTgwZDctN2Q2MmRiNjdmMzU3IiwidHlwZSI6IlBST0pFQ1QiLCJpYXQiOjE3NTM3ODczMjYsImV4cCI6NDkwOTU0NzMyNn0.FJljYq8LbO4Uh6c-2gRuAvaSzc-8xV_Lt1gyazQe8Ew"
  
  # Webhook Configuration
  WEBHOOK_URL = "https://your-backend-app.netlify.app/api/webhook"

# API routes
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

# CORS headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
