# Netlify configuration for NFT Marketplace Backend
# Functions removed due to 4KB environment variables limit
# Backend will be deployed separately

[build]
  # Skip build for backend - no functions to deploy
  command = "echo 'Backend functions disabled - deploy backend separately'"

  # No functions directory
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# No API routes - functions removed
# Backend will be deployed separately on a different platform
