# Netlify configuration for NFT Marketplace Backend
[build]
  # Build command for NestJS
  command = "pnpm run build"

  # Functions directory
  functions = "netlify/functions"

  # Node.js version and environment variables

# Plugin to auto-install function dependencies
[[plugins]]
  package = "@netlify/plugin-functions-install-core"
# ALL environment variables have been moved to Netlify's Environment Variables dashboard
# to avoid the 4KB AWS Lambda limit.
#
# Please set ALL required environment variables in your Netlify site settings:
# Site settings → Environment variables
#
# See NETLIFY_ENV_SETUP.md for the complete list of required variables.

[build.environment]
  NODE_VERSION = "18"

# API routes
[[redirects]]
  from = "/api/auth/*"
  to = "/.netlify/functions/auth"
  status = 200

[[redirects]]
  from = "/api/nft/*"
  to = "/.netlify/functions/nft"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api"
  status = 200

# CORS headers
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
